### ISSUE TITLE
Support for atom-ide-ui

### ISSUE THREAD

**Issue by Arcanemagus** [surdu/lint-scroll-marker#1]
As a heads up, it's relatively simple to also support [`atom-ide-ui`](https://github.com/facebook-atom/atom-ide-ui) once you have things already working for `linter-ui`. You can see an example of this in action over in [atom-minimap-linter](https://github.com/AtomLinter/atom-minimap-linter/blob/master/lib/minimap-linter.js).

If you have any questions feel free to message me on Atom's Slack 😉.

**Comment by surdu** [comment]
@Arcanemagus Thank you for your help !
